# Generated by Django 4.0.3 on 2022-03-05 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='last_name',
            field=models.CharField(default='None', max_length=255, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(default=0, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
